import yaml

# Emulate a user configuring the module.
module_config = dict()
with open(workflow.source_path("../../config/config.yaml"), "r") as f:
    module_config["module_co2stop_cdr"] = yaml.safe_load(f.read())


# Import the module and configure it.
# `snakefile:` specifies the module. It can use file paths and special github(...) / gitlab(...) markers
# `config`: specifies the module configuration.
# `pathvars:` helps you re-wire where the module places files.
module module_co2stop_cdr:
    snakefile:
        "../../workflow/Snakefile"
    config:
        module_config["module_co2stop_cdr"]
    pathvars:
        # Redirect specific user resources (inputs)
        user_shapes="resources/inputs/{shapes}/shapes.parquet",
        # Redirect specific module results (outputs)
        cdr_group="results/outputs/{shapes}/{scenario}/{cdr_group}.parquet",
        total_aggregate="results/outputs/{shapes}/{scenario}/totals.parquet",
        # Redirect module intermediate files
        logs="resources/co2stop_cdr/logs",
        resources="resources/co2stop_cdr/resources",
        results="resources/co2stop_cdr/results"


# rename all module rules with a prefix, to avoid naming conflicts.
use rule * from module_co2stop_cdr as module_co2stop_cdr_*


FILES = ["aquifer"]


# Request something from the module
rule all:
    message:
        "A generic test case for your module."
    default_target: True
    input:
        expand("results/outputs/BALK/medium/{cdr}.parquet", cdr=FILES),
